spring:
  profiles:
    active: core, database
  messages:
    encoding: UTF-8

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.doopai.litemall.core:  DEBUG