spring:
  profiles:
    active: database, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.doopai.litemall:  ERROR
    com.doopai.litemall.admin:  DEBUG